name: ETH Collector

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: node -v

      - run: npm install

      - run: npm list @supabase/supabase-js

      - run: echo "URL=$SUPABASE_URL"
        shell: bash

      - run: node collector.js

      - run: node analyzer.js
